Library
evansinho/Library pull request #1
Opened 2020-07-01 14:31 UTC by karthi07

The code has following implementation
 - Added Class for Books
 - constructor for the class
 - functions to addBook and Show book at homepage
 - added Event listener for buttons and form
 - Implemented LocalStorage to save books data

2020-07-01 22:01 UTC, shloch requested changes
## Hello @karthi07 , @evansinho 

Great project and work from you, works great
![bok](https://user-images.githubusercontent.com/40712459/86295755-38a2e980-bbef-11ea-926f-8b21c3623295.gif)

### [changes required]

- separate LOGIC from DOM MANIPULATION (you can split code into 2 `js` files and include them into `HTML` [see [requirements](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/section/dom_logic_separation_requirement.png)]

### [optional changes]
- Add a screenshot of your project inside your README file

### Waiting for the last review hopefully...great job

2020-07-03 06:01 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested requested changes.
You code is nicer now.
However, there are some issues that need to be fix.

1. I got this error when wanting to change the book status.
![Screenshot at 2020-07-03 06:53:45](https://user-images.githubusercontent.com/8848104/86436394-15b12c00-bcfa-11ea-8a3c-17b479313b2f.png)

2. There is no message, but an error in the console, when the user try to submit an empty form. Please, read the comment left below.

3. Those 2 are logic 
https://github.com/evansinho/Library/blob/ce3fa8cbda20dea7621781df9818bad2982393a0/dom.js#L39
https://github.com/evansinho/Library/blob/ce3fa8cbda20dea7621781df9818bad2982393a0/dom.js#L44
Move them out of DOM please.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-03 06:01 UTC, maelfosso commented on library.js
> +    throw 'error';
Instead of throwing an error in such an application, it's preferable to display a message to the user.

2020-07-04 06:43 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello coders,

Thank you for applying the changes. However, as indicated in the last review, there are still those two logic into the DOM. Please, move them into `logic.js` file.

Create two methods in `logic.js`: **delete** and **toggleReadStatus** and call them with the good parameters.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-07-04 06:43 UTC, maelfosso commented on dom.js
> +    myLibrary.splice(id, 1);
Follow the indication given up there, please.

2020-07-04 06:43 UTC, maelfosso commented on dom.js
> +    myLibrary[id].read = !myLibrary[id].read;
Follow the indications given up there

2020-07-06 08:34 UTC, Oghenebrume50 approved these changes
### APPROVED 

Hi @karthi07 @evansinho  this looks good to me :+1: please merge and move on **This is approved**

Nice project though, I love the UI :slightly_smiling_face: 

**RAPHAEL NORIODE** :mask:

2020-07-06 13:16 UTC, merged